### ISSUE TITLE
load_weights` requires h5py.  [Errno 10061] Unknown error

### ISSUE THREAD

**Issue by frankzhuo** [xuwenxue000/PJ_PREDICT_IMG#1]
![image](https://user-images.githubusercontent.com/8016063/34100421-529819f2-e41d-11e7-8ec4-309e3fa911e1.png)
area param: 281445 653100 [11, 3]
area param: 123396 653100 [11, 3]
`load_weights` requires h5py.
[Errno 10061] Unknown error
`load_weights` requires h5py.
[Errno 10061] Unknown error
[Errno 10061] Unknown error
{'info': {}, 'log': {}, 'debug': {'im0': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2048x1434 at 0x29F49E664A8>, 'im1': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2048x1434 at 0x29F49E66828>}, 'file_path_src': 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/2dbe3874-e3da-11e7-b185-28565a411a7c.jpg', 'time': 6}

不知道什么情况，麻烦gg 指导下

**Comment by frankzhuo** [comment]
项目很棒，继续学习，"cardno": "511124196812204434", "vinno": "LVTDB11B0FC029120" 我只弄出了两个

**Comment by xuwenxue000** [comment]
加油 ^_^

**Comment by frankzhuo** [comment]
大神gg ,你qq 多少啊，我想学习学习，剩下的我不会调试了

**Comment by xuwenxue000** [comment]
在这里提问题就好^_^,有比较完善的记录,我给在文档里加说明

**Comment by frankzhuo** [comment]
ϵͳ�Ҳ���ָ����·����
[Errno 2] No such file or directory: 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b/box\\0\\engineno.jpg.txt'
ϵͳ�Ҳ���ָ����·����
[Errno 2] No such file or directory: 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b/box\\0\\price.jpg.txt'
{'info': {'cardno': '130102198707041249', 'vinno': 'LSGHD5289FD298030'}, 'log': {'cardno_type': 'machine', 'vinno_type': 'machine'}, 'debug': {'im0': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2048x1434 at 0x291DD5860B8>, 'cardno_machine_default': '130102198707041249', 'predict_type_cardno': 'machine_cvfind', 'page_top': 0, 'vinno_machine_default': 'LSGHD5289FD298030'}, 'cardno_file': 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b/box\\0\\cardno.jpg_result.jpg', 'cardno_buildfile': 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b/box\\0\\cardno.jpg_result.jpgbuild.jpg', 'file_path_src': 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b.jpg', 'vinno_file': 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b/box\\0\\vinno.jpg_result.jpg', 'vinno_buildfile': 'D:\\code\\11_25\\PJ_PREDICT_IMG-master/data/invoice/upload/bccd7124-e46a-11e7-a1c3-2a565a411a7b/box\\0\\vinno.jpg_result.jpgbuild.jpg', 'time': 5}

gg ，我不会调试了，这个什么鬼 engineno.jpg.txt ，~~~~(>_<)~~~~

**Comment by xuwenxue000** [comment]
用tesseract命令识别会生成这个文件,然后读取这个文件内容的

**Comment by frankzhuo** [comment]
奥奥，不能识别 人民币符号。 弱弱的问下 tesseract 用的版本是？  ¥ 识别不出来

**Comment by xuwenxue000** [comment]
tesseract很久没有更新过了,只是一个备用方案,优化方向尽量使用机器学习的方式进行识别吧
