### ISSUE TITLE
MySQL数据结构语句

### ISSUE THREAD

**Issue by zhaofy66** [xuwenxue000/PJ_PREDICT_IMG#2]
楼主，没有MySQL数据结构生成语句吗？
![image](https://user-images.githubusercontent.com/30422995/35553742-0dffaf66-05d4-11e8-8e93-13da95b46bab.png)

**Comment by xuwenxue000** [comment]
DROP TABLE IF EXISTS `pe_invoice`;
CREATE TABLE `pe_invoice` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `file_src` text NOT NULL,
  `file_target` varchar(200) NOT NULL COMMENT '文件目标存储路径',
  `request_type` varchar(10) NOT NULL COMMENT '请求类型',
  `idcard` varchar(20) NOT NULL DEFAULT '' COMMENT '身份证号',
  `organ` varchar(20) NOT NULL DEFAULT '' COMMENT '机构编码',
  `vin` varchar(20) NOT NULL DEFAULT '' COMMENT 'vin码',
  `engine` varchar(50) NOT NULL DEFAULT '' COMMENT '发动机号码',
  `price` char(255) NOT NULL DEFAULT '' COMMENT '价格',
  `md5_code` varchar(40) NOT NULL COMMENT 'md5值',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态,0,初始化状态,1.已识别过,2,全部识别完毕,3.错误图片,4,疑难图片',
  `file_name` varchar(50) NOT NULL DEFAULT '' COMMENT '文件名称',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `predict_time` int(11) NOT NULL DEFAULT '0',
  `check_idcard` varchar(20) NOT NULL DEFAULT '',
  `check_organ` varchar(20) NOT NULL DEFAULT '',
  `check_price` varchar(20) NOT NULL DEFAULT '',
  `check_engine` varchar(50) NOT NULL DEFAULT '',
  `check_vin` varchar(50) NOT NULL DEFAULT '',
  `predict_type_idcard` varchar(50) NOT NULL DEFAULT '',
  `date` varchar(255) NOT NULL DEFAULT '',
  `invoice_no` varchar(255) NOT NULL DEFAULT '',
  `invoice_code` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
