### ISSUE TITLE
运行之后得不到任何结果

### ISSUE THREAD

**Issue by AndosonLiu** [xuwenxue000/PJ_PREDICT_IMG#3]
你好！
我按照你写的文档，把项目依赖的环境安装好了，并先后在ubuntu 1604和window 10下面运行了，但是传入你给的示例图片之后，2个接口都得不到任何结果（返回空的json串，或者票面文字都没有检测到）。请问能给我提供一下判断问题出在哪里的思路吗？
如图：
![url接口返回空json串](https://user-images.githubusercontent.com/9996308/36789605-1b89c5a8-1ccd-11e8-88fb-9bbc3906eb56.png)

![web接口返回数据缺少票面文字信息](https://user-images.githubusercontent.com/9996308/36789647-35426644-1ccd-11e8-8363-dcf26a10d54d.png)

**Comment by AndosonLiu** [comment]
你好，我找到了“运行之后得不到任何结果”问题所在：因为缺少`h5py`模块。
但是，我又碰见了新的问题：
1. 程序启动的时候，`h5py`抛出一个警告：


        D:\Python\VirtualEnvs\pj_predict_img_cpu\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

2. 检测不到“机构代码”、“发动机号码”和“金额”，并且有如下错误提示：


        area param: 281445 653100 [11, 3]
        area param: 123396 653100 [11, 3]
        ====maching_text_default:130102198707041249
        ====maching_text_default:LSGHD5289FD298030
        系统找不到指定路径
        [Errno 2] No such file or directory: 'D:\\ProjectRepository\\pj_predict_img/data/invoice/upload/c18b8898-1cf9-11e8-a180-7085c26ccddf/box\\0\\engineno.jpg.txt'
        系统找不到指定路径
        [Errno 2] No such file or directory: 'D:\\ProjectRepository\\pj_predict_img/data/invoice/upload/c18b8898-1cf9-11e8-a180-7085c26ccddf/box\\0\\price.jpg.txt'

对于上述警告，我按照网上的博客，重新安装numpy (1.14.1+mkl)，但还是不能避免；请问，该警告会对程序运行有什么影响吗？为什么没有engineno.jpg.txt和price.jpg.txt呢？多谢抽空查看。

**Comment by xuwenxue000** [comment]
第一个问题警告问题应该没关系
第二个找不到 txt 的这个问题,是使用了另外一个识别工具生成这个 txt,如果生成失败,就会没有这个文件,在报这个错误的地方加一个判断吧,如果没这个文件就返回空
