### ISSUE TITLE
你好，我运行起来访问demo页无法访问到，是怎么回事？

### ISSUE THREAD

**Issue by leopard55** [xuwenxue000/PJ_PREDICT_IMG#4]

**Comment by Sunshinelz** [comment]
你好，访问完接口，控制台出现如下输出，请问怎么解决？谢谢你
![_20181126235640](https://user-images.githubusercontent.com/22102730/49025578-f6295780-f1d6-11e8-8de3-7ebcafcaf889.png)

**Comment by Sunshinelz** [comment]
你好，访问完接口，控制台出现如下输出，请问怎么解决？谢谢你

![Uploading 123.png…]()

**Comment by Sunshinelz** [comment]
你好，访问完接口，控制台出现如下输出，请问怎么解决？谢谢你

![123](https://user-images.githubusercontent.com/22102730/49027201-a056ae80-f1da-11e8-8d58-68e0ec828d9b.png)
